stages:
  - docs
  - deploy

# Common variables
variables:
  FEDORA_IMAGE: "registry.gitlab.gnome.org/gnome/gtk/fedora:v49"

reference:
  image: $FEDORA_IMAGE
  stage: docs
  needs: []
  script:
    - export PATH="$HOME/.local/bin:$PATH"
    - pip3 install --user meson
    - sh -x ./download-reference.sh
    - sh -x ./prepare-docs.sh docs
  artifacts:
    paths:
      - docs

pages:
  stage: deploy
  needs: ['reference']
  script:
    - sh -x ./publish.sh docs static public
  artifacts:
    paths:
      - public
  only:
    - docs-gtk-org@GNOME/gtk
